function pic() {
    var bgm = ['cxrsxdxmxgxs/cxrsxdxmxgxs_001.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_002.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_003.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_004.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_005.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_006.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_007.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_008.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_009.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_010.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_011.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_012.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_013.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_014.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_015.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_016.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_017.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_018.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_019.png',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_020.png',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_021.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_022.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_023.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_024.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_025.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_026.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_027.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_028.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_029.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_030.png',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_031.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_032.png',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_033.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_034.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_035.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_036.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_037.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_038.png',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_039.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_040.png',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_041.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_042.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_043.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_044.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_045.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_046.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_047.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_048.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_049.jpg',
    'cxrsxdxmxgxs/cxrsxdxmxgxs_050.jpg'
  ];



  $('body').css({
      'background':'url(' + bgm[Math.floor(Math.random() * bgm.length)] + ')',
      'background-repeat': 'repeat', '-webkit-background-repeat' : 'repeat', '-moz-background-repeat' : 'repeat', '-o-background-repeat' : 'repeat',
      'background-position': 'center center', '-webkit-background-position' : 'center center',
                             '-moz-background-position' : 'center center', '-o-background-position' : 'center center',
      'background-attachment': 'fixed', '-webkit-background-attachment' : 'fixed', '-moz-background-attachment' : 'fixed', '-o-background-attachment' : 'fixed',
      'background-size' : 'contain', '-webkit-background-size' : 'contain', '-moz-background-size' : 'contain', '-o-background-size' : 'contain',
  });
}

pic();
